name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.8
        id: go
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Build
        run: make build
      - name: Test
        run: make test
