---
name: updatecli

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: '0 0 * * *'
  push:
  pull_request:
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Diff
        uses: updatecli/updatecli-action@v1.24.0
        with:
          command: diff
          flags: "--config ./updatecli/daily.d --values ./updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Apply
        uses: updatecli/updatecli-action@v1.24.0
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        with:
          command: apply
          flags: "--config ./updatecli/daily.d --values ./updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
