---
name: updatecli

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"
  push:
  pull_request:
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Diff
        uses: updatecli/updatecli-action@v1.31.0
        with:
          command: diff
          flags: "--config ./updatecli/daily.d --values ./updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: tibdex/github-app-token@v1.5
        id: generate_token
        if: github.ref == 'refs/heads/main'
        with:
          app_id: ${{ secrets.JENKINS_ADMIN_APP_ID }}
          private_key: ${{ secrets.JENKINS_ADMIN_APP_PRIVKEY }}
      - name: Apply
        uses: updatecli/updatecli-action@v1.31.0
        if: github.ref == 'refs/heads/main'
        with:
          command: apply
          flags: "--config ./updatecli/daily.d --values ./updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
